/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package concurrentsearch;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class MainThreadTest {
    @Test void getRandomNumber() {
        MainThread classUnderTest = new MainThread();
        assertNotNull(classUnderTest.getRandomNumber(1), "get random should always return a Integer");
    }
}
